module.exports = [
  { name: 'Liverpool FC', location: 'Merseyside' },
  { name: 'Arsenal FC', location: 'North London' },
  { name: 'WestHam United FC', location: 'London' },
  { name: 'Espanyol FC', location: 'Barcelona' },
  { name: 'FC Barcelona', location: 'Barcelona' },
  { name: 'Real Madrid', location: 'Madrid' },
  { name: 'Atletico de Madrid', location: 'Madrid' },
  { name: 'Valencia', location: 'Valencia' },
  { name: 'Sevilla', location: 'Seville' },
  { name: 'Internazionale Milan', location: 'Milan' },
  { name: 'Juventus', location: 'Turin' },
  { name: 'AC Milan', location: 'Milano' },
  { name: 'PSG', location: 'Paris' },
  { name: 'Lyon', location: 'Lyon' },
  { name: 'Bayern Munich', location: 'Munich' },
  { name: 'LA Galaxy', location: 'Los Angeles' },
  { name: 'FC Santos', location: 'Rio' },
  { name: 'Enyinba FC', location: 'Aba' },
  { name: 'Gateway United', location: 'Abeokuta' },
  { name: 'Lagos FC', location: 'Lagos' },
];
